services:
  ################################
  # required services
  #
  # - temporal: for workflow management
  # - zitadel: for identity and access management (maybe)
  # - questdb: for time series data (evalutation)
  # - clickhouse: for time series data (evaluation)
  ################################

  # temporal.io

  temporal-db:
    container_name: temporal-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${TEMPORAL__DB_USER}
      POSTGRES_PASSWORD: ${TEMPORAL__DB_PASS}
      POSTGRES_DB: ${TEMPORAL__DB_NAME}
    volumes:
      - temporal-db-data:/var/lib/postgresql/data
    networks:
      - ctrlplane

  temporal:
    container_name: temporal
    depends_on:
      - temporal-db
    environment:
      # https://github.com/temporalio/temporal/blob/main/docker/config_template.yaml#L102
      DB: postgres12_pgx
      DBNAME: ${TEMPORAL__DB_NAME}
      DB_PORT: 5432
      POSTGRES_USER: ${TEMPORAL__DB_USER}
      POSTGRES_PWD: ${TEMPORAL__DB_PASS}
      POSTGRES_SEEDS: temporal-db
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.25.1
    ports:
      - 7233:7233
    volumes:
      - ./tools/temporal/dynamicconfig/:/etc/temporal/config/dynamicconfig/
    networks:
      - ctrlplane

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    image: temporalio/ui:2.33.0
    ports:
      - 8080:8080
    networks:
      - ctrlplane

  ################################
  # clickhouse.io
  ################################

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8
    environment:
      CLICKHOUSE_DB: ${PULSE__CH__NAME}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: ${PULSE__CH__USER}
      CLICKHOUSE_PASSWORD: ${PULSE__CH__PASS}
    ports:
      - "6665:8123"
      - "6666:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server/
    networks:
      - ctrlplane

  ################################
  # quantm.io ctrlplane
  ################################

  ctrlplane-db:
    container_name: ctrlplane-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - ctrlplane-db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - ctrlplane

################################
# network and storage
################################

networks:
  ctrlplane: {}

volumes:
  temporal-db-data: {}
  questdb-data: {}
  clickhouse-data: {}
  clickhouse-logs: {}
  ctrlplane-db-data: {}
