package: auth
generate:
  models: true
  echo-server: true
import-mapping:
  '../shared/openapi.spec.yaml': go.breu.io/ctrlplane/internal/shared
  '../entity/openapi.spec.yaml': go.breu.io/ctrlplane/internal/entity
compatibility:
  always-prefix-enum-values: true
output: openapi.gen.go
output-options:
  user-templates-dir: ../shared/templates
