name: Release quantm
on: [pull_request, workflow_dispatch]

jobs:
  release-artifact:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t quantm/ctrlplane:latest .
          docker tag quantm/ctrlplane:latest europe-west3-docker.pkg.dev/quantm-dev-400720/cloud-run-source-deploy/quantm/ctrlplane:latest
          docker tag quantm/ctrlplane:latest europe-west3-docker.pkg.dev/quantm-dev-400720/cloud-run-source-deploy/quantm/ctrlplane:${{ steps.vars.outputs.short_sha }}

      - name: docker ls
        run: docker image ls

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "${{ secrets.GCP_WORLDLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SA_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          access_token_lifetime: 300s

      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev/quantm-dev-400720/cloud-run-source-deploy/
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            europe-west3-docker.pkg.dev/quantm-dev-400720/cloud-run-source-deploy/quantm/ctrlplane:${{ steps.vars.outputs.short_sha }}
            europe-west3-docker.pkg.dev/quantm-dev-400720/cloud-run-source-deploy/quantm/ctrlplane:latest
